### PR TITLE
Correct current and next seasons

### PR DESCRIPTION
**Pull request by jac4e**
Implements some simple logic so 'Popular This Season' and 'Upcoming Next Season' views fetch using the correct seasons

### CODE REVIEW

**Comment by Goldenfreddy0703** [comment]
Hey thank you so much for correcting current and next seasons. I'm not sure if this has already been fixed with the beta version of kaito but do you think you could help us with implanting this into the beta version. 

We have discussion groups talking about bugs and fixes and i think we could use your help on that. 
Here is the link if you would like to help us: https://github.com/SwagOtaku/plugin.video.kaito/discussions/99

Again, Thank you

**Comment by jac4e** [comment]
The 0.0.11 beta does not include something like this. I would like to help, but as I said in the discussion thread, it is difficult and messy to help fix bugs and implement new features for the beta while it's not on a branch in this repository.

For now I am just focusing on improving my own experience with v0.0.10, and creating pull requests for simple features that can be migrated to v0.0.11 with no issues.

**Comment by Goldenfreddy0703** [comment]
Ah, I understand. Thank you

**Comment by meesterexx** [comment]
Just tested this in .11 beta by directly editing AniListBrowser.py with the code changes in the commit and seems to work fine. Section results in addon match whats on:
https://anilist.co/search/anime/this-season
https://anilist.co/search/anime/next-season

**Pull request closed without merging**
