### PR TITLE
Kodi Leia+Matrix compatibility using six and kodi-six

### LINKED ISSUE #47: Kodi 19 (Matrix) Support
Seems Kodi has moved everything to Python3 in version 19, and all the AddOns need to be updated accordingly. Please let us know where we can send Pocky.

### PR DESCRIPTION
**Pull request by Gujal00**
Converted the code using six and Kodi-six libraries to make it work on both Kodi Leia and Matrix
Also fixed some errors in Alldebrid relating to magnets cache check
Fixes #47

### CODE REVIEW

**Comment by TaiDak** [comment]
Hi Guja00, I tested your build, and it there seems to be a typeerror. Happens when you open an series you haven't opened before, and the error stops on that a series you already opened. This affects kodi Leia and Matrix. Also on Leia, when you try to play an episode, Kodi become stuck on the scraping screen, not even pressing back cancels it. This bug only affects Leia, on Matrix, apart from the typeerror, Kaito works perfectly, and your fix for alldebrid works awesome.

**Comment by Gujal00** [comment]
Thanks for the feedback @TaiDak will check the typeerror issue.

**Comment by TaiDak** [comment]
My apologies, forgot to add log, https://paste.kodi.tv/ilezezanut

**Comment by Gujal00** [comment]
@TaiDak TypeError is fixed in both Leia and Matrix. get the latest commit for testing
Checking the scrape hang in Leia now

**Comment by Goldenfreddy0703** [comment]
Hey, i just wanna say thank you for making this compatible with Kodi 19 Matrix. Honestly, i love this addon and i hope this addon does not go down like the Humming Bird addon. I do have one question tho and its not related to any errors or anything but are you the same guy who made this addon capable with Kodi 19 Matrix or was that i different person?
https://www.reddit.com/r/Addons4Kodi/comments/ls3pxe/release_kaito_kodi_19_port

**Comment by Goldenfreddy0703** [comment]
Hey, really quick, i found an error in the watchlist category if you Update Watchlist to Kitsu, you will get an error when you play an anime.  

Here is the Log error it gives and thats the only error i found so far but everything else is amazing. 

```
2021-04-05 01:52:37.195 T:9312     INFO <general>: VideoPlayer::OpenFile: plugin://plugin.video.kaito/play/124080/1/
2021-04-05 01:52:37.666 T:4332     INFO <general>: Creating InputStream
2021-04-05 01:52:37.787 T:1640    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'data'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\jenki\Desktop\Kodi 19 Fixes\portable_data\addons\plugin.video.kaito\default.py", line 366, in <module>
                                                       router_process(control.get_plugin_url(), control.get_plugin_params())
                                                     File "C:\Users\jenki\Desktop\Kodi 19 Fixes\portable_data\addons\plugin.video.kaito\resources\lib\ui\router.py", line 68, in router_process
                                                       return route_obj.func(payload, params)
                                                     File "C:\Users\jenki\Desktop\Kodi 19 Fixes\portable_data\addons\plugin.video.kaito\default.py", line 314, in PLAY
                                                       player.play_source(link,
                                                     File "C:\Users\jenki\Desktop\Kodi 19 Fixes\portable_data\addons\plugin.video.kaito\resources\lib\ui\player.py", line 296, in play_source
                                                       watchlistPlayer().handle_player(anilist_id, watchlist_update, build_playlist, episode, filter_lang)
                                                     File "C:\Users\jenki\Desktop\Kodi 19 Fixes\portable_data\addons\plugin.video.kaito\resources\lib\ui\player.py", line 60, in handle_player
                                                       self._watchlist_update = watchlist_update(anilist_id, episode)
                                                     File "C:\Users\jenki\Desktop\Kodi 19 Fixes\portable_data\addons\plugin.video.kaito\resources\lib\WatchlistIntegration.py", line 133, in watchlist_update
                                                       return WatchlistFlavor.watchlist_update_request(anilist_id, episode)
                                                     File "C:\Users\jenki\Desktop\Kodi 19 Fixes\portable_data\addons\plugin.video.kaito\resources\lib\WatchlistFlavor\__init__.py", line 71, in watchlist_update_request
                                                       return WatchlistFlavor.get_update_flavor().watchlist_update(anilist_id, episode)
                                                     File "C:\Users\jenki\Desktop\Kodi 19 Fixes\portable_data\addons\plugin.video.kaito\resources\lib\WatchlistFlavor\Kitsu.py", line 275, in watchlist_update
                                                       if len(item_dict['data']) == 0:
                                                   KeyError: 'data'
                                                   -->End of Python script error report<--
```

**Comment by Gujal00** [comment]
@Goldenfreddy0703 
No that reddit post is not me. That code is not backward compatible with Kodi 18
The goal of this PR is to get a codebase that works on both Kodi 18 and 19

**Comment by Goldenfreddy0703** [comment]
Honestly I feel dumb and I did not know that one addon would be compatible with both python 2 and python 3. I thought they were in separate projects. Now I feel dumb but thank you for telling me that. 😅

**Comment by Gujal00** [comment]
@TaiDak Havent figured out yet why the code is failing on Leia
```
Traceback (most recent call last):
  File "D:\kodi\system\python\Lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "D:\kodi\system\python\Lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\kodi\portable_data\addons\plugin.video.kaito\resources\lib\pages\__init__.py", line 144, in getSources
    self.close()
  File "D:\kodi\portable_data\addons\plugin.video.kaito\resources\lib\windows\get_sources_window.py", line 86, in close
    control.dialogWindow.close(self)
TypeError: unbound method wrapped_func_close() must be called with wrapped_class_WindowDialog instance as first argument (got Sources instance instead)
```
In both cases the argument is identical though
```
Matrix <resources.lib.pages.Sources object at 0x000002101FABFE00>
Leia <resources.lib.pages.Sources object at 0x0000028238AF8F48>
```
The addon works correctly in Matrix though

**Comment by Goldenfreddy0703** [comment]
> 
> 
> @TaiDak Havent figured out yet why the code is failing on Leia
> 
> ```
> Traceback (most recent call last):
>   File "D:\kodi\system\python\Lib\threading.py", line 801, in __bootstrap_inner
>     self.run()
>   File "D:\kodi\system\python\Lib\threading.py", line 754, in run
>     self.__target(*self.__args, **self.__kwargs)
>   File "D:\kodi\portable_data\addons\plugin.video.kaito\resources\lib\pages\__init__.py", line 144, in getSources
>     self.close()
>   File "D:\kodi\portable_data\addons\plugin.video.kaito\resources\lib\windows\get_sources_window.py", line 86, in close
>     control.dialogWindow.close(self)
> TypeError: unbound method wrapped_func_close() must be called with wrapped_class_WindowDialog instance as first argument (got Sources instance instead)
> ```
> 
> In both cases the argument is identical though
> 
> ```
> Matrix <resources.lib.pages.Sources object at 0x000002101FABFE00>
> Leia <resources.lib.pages.Sources object at 0x0000028238AF8F48>
> ```
> 
> The addon works correctly in Matrix though

I think its due to the plugins this addon needs, some of the dependencies are updated and some of them are missing from Leia which is why they might not be working.

**Comment by Gujal00** [comment]
@TaiDak @Goldenfreddy0703 
Kodi 18 issue sorted. Please test the code on both Matrix and Leia. It is all working as far as I could test

**Comment by Goldenfreddy0703** [comment]
I will test it tomorrow sense it's 2 am for me. Was it the dependencies that was causing the errors?

**Comment by Gujal00** [comment]
> 
> 
> I will test it tomorrow sense it's 2 am for me. Was it the dependencies that was causing the errors?

xbmcgui wrapper inside kodi-six has an issue, so using that library without wrapping through kodi-six

**Comment by Fatal-Errol** [comment]
Tried this but it returns an error when authorizing MAL and Anilist

I also tried to load my old data with saved MAL and Anilist auth but the listing also fails.

https://paste.kodi.tv/ijiyakewis.kodi

**Comment by Gujal00** [comment]
@Fatal-Errol please provide full debug log, not snippets

**Comment by SwagOtaku** [comment]
i think the kodi-six module might be causing issues, i created a zip file using the future module. Let me know how it works on matrix

https://github.com/SwagOtaku/plugin.video.kaito/archive/refs/heads/test-matrix.zip

**Comment by Gujal00** [comment]
@SwagOtaku The future module depends on certain other modules which are not available on all platforms, hence I tend to stay away from future (which I used to earlier and then moved to six).
Kodi-six is not six and the stuff kodi-six addresses is not in either future or six, it is specific to kodi string handling

**Comment by Gujal00** [comment]
@Fatal-Errol @TaiDak @Goldenfreddy0703 
I have fixed the watchlist integration in my latest commit and tested with MAL. 
Please test and report back

**Comment by SwagOtaku** [comment]
@Gujal00 i'm going to push update with the addon using future module. I prefer future over six, but i understand where you're coming from with using six. 

Keep this pull request up, so if people run into issues on LibreElec/iOS/TVOS they can see and test out your fork.

**Comment by SwagOtaku** [comment]
@Gujal00 also can you make a separate pull request that fixes errors in Alldebrid

**Comment by Gujal00** [comment]
> 
> 
> @Gujal00 also can you make a separate pull request for the fixes for Alldebrid

I have raised a PR just for alldebrid fix on the main branch

**Comment by Gujal00** [comment]
> 
> 
> @Gujal00 i'm going to push update with the addon using future module. I prefer future over six, but i understand where you're coming from with using six.
> 
> Keep this pull request up, so if people run into issues on LibreElec/iOS/TVOS they can see and test out your fork.

I went through your code based on future and it looks like you have only addressed py2/3 differences.
There are lot of differences in xbmc.python in matrix which you seem to have left out, so the code will break in matrix.
E.g, Line1, Line2, Line3 is removed from all dialogs and replaced with msg
translatePath moved from xbmc to xbmcvfs
xbmc.LOGNOTICE deprecated etc.
Have a l[ook at this](https://forum.kodi.tv/showthread.php?tid=344263) for full changes of the xbmc.python api

**Comment by TaiDak** [comment]
@Gujal00 your latest commit works perfectly as of right now, on Shield TV Pro 2019 Kodi 18. No issues with all debrid, or watchlist, using Kitsu btw.

**Comment by Gujal00** [comment]
> 
> 
> @Gujal00 your latest commit works perfectly as of right now, on Shield TV Pro 2019 Kodi 18. No issues with all debrid, or watchlist, using Kitsu btw.

Thanks for the feedback. So I have tested with MAL and you have with Kitsu. If @Fatal-Errol also tests and confirms as he is using Anilist, then we have the watchlist working correctly in Matrix and Leia with this fork

And for anyone who wants to test this code, you can [get the zip here](https://gujal00.github.io/plugin.video.kaito-0.1.0.zip)
The same zip works on both Matrix and Leia

**Comment by tieu1991** [comment]
The last update 0.0.9 won't install on kodi matrix because it try to import xbmc.python v2.26.0

**Comment by Gujal00** [comment]
> The last update 0.0.9 won't install on kodi matrix because it try to import xbmc.python v2.26.0
That has got nothing to do with this PR, please open new issue to report problems with 0.0.9.

This PR is not merged yet and if you want to test use the provided zip above

**Comment by Gujal00** [comment]
Abandoning this as the code has now diverged a lot

**Pull request closed without merging**
